/* eslint-disable prettier/prettier */

export const DEFAULT_SAMPLE_DATA_SET = [
  {id: 1, name: 'SOLAR PANEL ARRAY', earning_power: 900, slider_martia: 50, slider_resource: 50, owner_health: 76, owner_fee: 5, passive_multiplier_pct: 25, martia_multiplier: 3.0, order: 1},
  {id: 2, name: 'FISSION REACTOR', earning_power: 645, slider_martia: 50, slider_resource: 50, owner_health: 99, owner_fee: 15, passive_multiplier_pct: 25, martia_multiplier: 3.0, order: 2},
  {id: 3, name: 'MEGAPOWER REACTOR', earning_power: 185, slider_martia: 75, slider_resource: 25, owner_health: 88, owner_fee: 5, passive_multiplier_pct: 25, martia_multiplier: 3.0, order: 3},
  {id: 4, name: 'ICE MINING RIG', earning_power: 800, slider_martia: 25, slider_resource: 75, owner_health: 90, owner_fee: 17, passive_multiplier_pct: 25, martia_multiplier: 3.0, order: 4},
  {id: 5, name: 'INFLATABLE SLEEPING POD', earning_power: 761, slider_martia: 75, slider_resource: 25, owner_health: 73, owner_fee: 16, passive_multiplier_pct: 25, martia_multiplier: 3.0, order: 5},
  {id: 6, name: 'CONSTRUCTION UTILITY VEHICLE', earning_power: 403, slider_martia: 75, slider_resource: 25, owner_health: 77, owner_fee: 20, passive_multiplier_pct: 25, martia_multiplier: 3.0, order: 6},
  {id: 7, name: 'SMALL EXCAVATOR', earning_power: 641, slider_martia: 75, slider_resource: 25, owner_health: 93, owner_fee: 12, passive_multiplier_pct: 25, martia_multiplier: 3.0, order: 7},
  {id: 8, name: 'WEATHER OUTPOST', earning_power: 220, slider_martia: 75, slider_resource: 25, owner_health: 88, owner_fee: 1, passive_multiplier_pct: 25, martia_multiplier: 3.0, order: 8},
  {id: 9, name: 'ROVER', earning_power: 276, slider_martia: 100, slider_resource: 0, owner_health: 81, owner_fee: 4, passive_multiplier_pct: 25, martia_multiplier: 4.0, order: 9},
  {id: 10, name: 'SCOUTING DRONE', earning_power: 255, slider_martia: 100, slider_resource: 0, owner_health: 74, owner_fee: 15, passive_multiplier_pct: 25, martia_multiplier: 4.0, order: 10},
  {id: 11, name: 'BUGGY', earning_power: 258, slider_martia: 100, slider_resource: 0, owner_health: 74, owner_fee: 13, passive_multiplier_pct: 25, martia_multiplier: 4.0, order: 11},
  {id: 12, name: 'QUAD BIKE', earning_power: 611, slider_martia: 100, slider_resource: 0, owner_health: 80, owner_fee: 17, passive_multiplier_pct: 25, martia_multiplier: 4.0, order: 12},
  {id: 14, name: 'BATTERY ARRAY', earning_power: 302, slider_martia: 100, slider_resource: 0, owner_health: 75, owner_fee: 9, passive_multiplier_pct: 25, martia_multiplier: 4.5, order: 14},
  {id: 18, name: 'FUEL PLANT', earning_power: 419, slider_martia: 25, slider_resource: 75, owner_health: 89, owner_fee: 10, passive_multiplier_pct: 25, martia_multiplier: 4.0, order: 18},
  {id: 19, name: '3D PRINTING ROBOT', earning_power: 193, slider_martia: 50, slider_resource: 50, owner_health: 85, owner_fee: 7, passive_multiplier_pct: 25, martia_multiplier: 4.0, order: 19},
  {id: 20, name: 'INFLATABLE GREENHOUSE', earning_power: 646, slider_martia: 100, slider_resource: 0, owner_health: 75, owner_fee: 18, passive_multiplier_pct: 25, martia_multiplier: 4.0, order: 20},
  {id: 21, name: 'MALE ENGINEER', earning_power: 924, slider_martia: 25, slider_resource: 75, owner_health: 76, owner_fee: 19, passive_multiplier_pct: 25, martia_multiplier: 5.5, order: 21},
  {id: 22, name: 'FEMALE ENGINEER', earning_power: 26, slider_martia: 25, slider_resource: 75, owner_health: 84, owner_fee: 3, passive_multiplier_pct: 25, martia_multiplier: 5.5, order: 22},
  {id: 23, name: 'MALE SCIENTIST', earning_power: 687, slider_martia: 25, slider_resource: 75, owner_health: 98, owner_fee: 12, passive_multiplier_pct: 25, martia_multiplier: 5.5, order: 23},
  {id: 24, name: 'FEMALE SCIENTIST', earning_power: 556, slider_martia: 75, slider_resource: 25, owner_health: 98, owner_fee: 17, passive_multiplier_pct: 25, martia_multiplier: 5.5, order: 24},
  {id: 25, name: 'MALE BOTANIST', earning_power: 377, slider_martia: 25, slider_resource: 75, owner_health: 79, owner_fee: 3, passive_multiplier_pct: 25, martia_multiplier: 5.5, order: 25},
  {id: 26, name: 'FEMALE BOTANIST', earning_power: 71, slider_martia: 50, slider_resource: 50, owner_health: 76, owner_fee: 18, passive_multiplier_pct: 25, martia_multiplier: 5.5, order: 26},
  {id: 27, name: 'MALE DOCTOR', earning_power: 996, slider_martia: 100, slider_resource: 0, owner_health: 70, owner_fee: 5, passive_multiplier_pct: 25, martia_multiplier: 5.5, order: 27},
  {id: 28, name: 'FEMALE DOCTOR', earning_power: 502, slider_martia: 100, slider_resource: 0, owner_health: 91, owner_fee: 1, passive_multiplier_pct: 25, martia_multiplier: 5.5, order: 28},
  {id: 29, name: 'MALE CIVIL ENGINEER', earning_power: 327, slider_martia: 75, slider_resource: 25, owner_health: 97, owner_fee: 10, passive_multiplier_pct: 25, martia_multiplier: 5.5, order: 29},
  {id: 30, name: 'FEMALE CIVIL ENGINEER', earning_power: 590, slider_martia: 75, slider_resource: 25, owner_health: 87, owner_fee: 8, passive_multiplier_pct: 25, martia_multiplier: 5.5, order: 30},
  {id: 31, name: 'MALE GEOLOGIST', earning_power: 767, slider_martia: 100, slider_resource: 0, owner_health: 95, owner_fee: 1, passive_multiplier_pct: 25, martia_multiplier: 5.5, order: 31},
  {id: 32, name: 'FEMALE GEOLOGIST', earning_power: 552, slider_martia: 100, slider_resource: 0, owner_health: 95, owner_fee: 4, passive_multiplier_pct: 25, martia_multiplier: 5.5, order: 32},
  {id: 35, name: 'MALE SECURITY', earning_power: 902, slider_martia: 75, slider_resource: 25, owner_health: 71, owner_fee: 11, passive_multiplier_pct: 25, martia_multiplier: 5.5, order: 35},
  {id: 36, name: 'FEMALE SECURITY', earning_power: 83, slider_martia: 100, slider_resource: 0, owner_health: 74, owner_fee: 17, passive_multiplier_pct: 25, martia_multiplier: 5.5, order: 36},
  {id: 37, name: 'ICE MINING PLANT', earning_power: 214, slider_martia: 25, slider_resource: 75, owner_health: 94, owner_fee: 2, passive_multiplier_pct: 25, martia_multiplier: 7.0, order: 37},
  {id: 38, name: 'INFLATABLE LABORATORY', earning_power: 307, slider_martia: 100, slider_resource: 0, owner_health: 84, owner_fee: 1, passive_multiplier_pct: 25, martia_multiplier: 7.0, order: 38},
  {id: 39, name: 'FUEL GENERATOR', earning_power: 335, slider_martia: 75, slider_resource: 25, owner_health: 92, owner_fee: 18, passive_multiplier_pct: 25, martia_multiplier: 7.0, order: 39},
  {id: 40, name: 'INFLATABLE DINING HALL', earning_power: 260, slider_martia: 100, slider_resource: 0, owner_health: 94, owner_fee: 5, passive_multiplier_pct: 25, martia_multiplier: 7.0, order: 40},
  {id: 41, name: 'INFLATABLE SOCIAL HUB', earning_power: 131, slider_martia: 100, slider_resource: 0, owner_health: 97, owner_fee: 20, passive_multiplier_pct: 25, martia_multiplier: 7.0, order: 41},
  {id: 42, name: 'SMALL HOUSE', earning_power: 34, slider_martia: 25, slider_resource: 75, owner_health: 97, owner_fee: 5, passive_multiplier_pct: 25, martia_multiplier: 7.0, order: 42},
  {id: 43, name: 'MEDICAL BAY', earning_power: 498, slider_martia: 100, slider_resource: 0, owner_health: 72, owner_fee: 17, passive_multiplier_pct: 25, martia_multiplier: 7.0, order: 43},
  {id: 44, name: 'GREENHOUSE', earning_power: 90, slider_martia: 100, slider_resource: 0, owner_health: 78, owner_fee: 18, passive_multiplier_pct: 25, martia_multiplier: 7.0, order: 44},
  {id: 45, name: 'LINEAR RAIL 3D PRINTER', earning_power: 300, slider_martia: 25, slider_resource: 75, owner_health: 73, owner_fee: 2, passive_multiplier_pct: 25, martia_multiplier: 7.0, order: 45},
  {id: 46, name: 'MAINTENANCE & CHARGING STATION', earning_power: 139, slider_martia: 25, slider_resource: 75, owner_health: 75, owner_fee: 14, passive_multiplier_pct: 25, martia_multiplier: 7.0, order: 46},
  {id: 47, name: 'MULTI PURPOSE WORKSHOP', earning_power: 831, slider_martia: 25, slider_resource: 75, owner_health: 98, owner_fee: 17, passive_multiplier_pct: 25, martia_multiplier: 7.0, order: 47},
  {id: 50, name: 'COMMUNICATION ARRAY', earning_power: 248, slider_martia: 100, slider_resource: 0, owner_health: 100, owner_fee: 20, passive_multiplier_pct: 25, martia_multiplier: 7.0, order: 50},
  {id: 51, name: 'CARGO ROCKETSHIP', earning_power: 879, slider_martia: 50, slider_resource: 50, owner_health: 84, owner_fee: 3, passive_multiplier_pct: 25, martia_multiplier: 7.0, order: 51},
  {id: 52, name: 'CREW ROCKETSHIP', earning_power: 469, slider_martia: 50, slider_resource: 50, owner_health: 90, owner_fee: 7, passive_multiplier_pct: 25, martia_multiplier: 7.0, order: 52},
  {id: 56, name: 'LOW PRESSURE STORAGE TANK', earning_power: 260, slider_martia: 100, slider_resource: 0, owner_health: 96, owner_fee: 18, passive_multiplier_pct: 25, martia_multiplier: 4.5, order: 56},
  {id: 57, name: 'SMALL STORAGE STRUCTURE', earning_power: 160, slider_martia: 100, slider_resource: 0, owner_health: 75, owner_fee: 8, passive_multiplier_pct: 25, martia_multiplier: 5.0, order: 57},
  {id: 58, name: 'HIGH PRESSURE STORAGE TANK', earning_power: 464, slider_martia: 100, slider_resource: 0, owner_health: 76, owner_fee: 18, passive_multiplier_pct: 25, martia_multiplier: 4.5, order: 58},
];
