/* eslint-disable prettier/prettier */
import { v4 as uuidv4 } from 'uuid';

export const ITEM_RESOURCE_INPUTS = [
  { id: uuidv4(), item_id: 4, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000110 },
  { id: uuidv4(), item_id: 5, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000110 },
  { id: uuidv4(), item_id: 6, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000110 },
  { id: uuidv4(), item_id: 7, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000110 },
  { id: uuidv4(), item_id: 8, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000110 },
  { id: uuidv4(), item_id: 9, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000110 },
  { id: uuidv4(), item_id: 10, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000110 },
  { id: uuidv4(), item_id: 11, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000110 },
  { id: uuidv4(), item_id: 12, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000110 },
  { id: uuidv4(), item_id: 13, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000110 },
  { id: uuidv4(), item_id: 14, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000330 },
  { id: uuidv4(), item_id: 15, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000000 },
  { id: uuidv4(), item_id: 16, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000000 },
  { id: uuidv4(), item_id: 17, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000000 },
  { id: uuidv4(), item_id: 18, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.001520 },
  { id: uuidv4(), item_id: 19, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.001420 },
  { id: uuidv4(), item_id: 20, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.001560 },
  { id: uuidv4(), item_id: 21, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 22, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 23, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 24, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 25, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 26, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 27, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 28, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 29, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 30, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 31, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 32, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 33, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 34, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 35, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 36, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.002920 },
  { id: uuidv4(), item_id: 37, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.004400 },
  { id: uuidv4(), item_id: 38, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.004840 },
  { id: uuidv4(), item_id: 39, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.005020 },
  { id: uuidv4(), item_id: 40, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.004320 },
  { id: uuidv4(), item_id: 41, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.004400 },
  { id: uuidv4(), item_id: 42, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.004400 },
  { id: uuidv4(), item_id: 43, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.004400 },
  { id: uuidv4(), item_id: 44, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.004440 },
  { id: uuidv4(), item_id: 45, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.004410 },
  { id: uuidv4(), item_id: 46, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.004180 },
  { id: uuidv4(), item_id: 47, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.004290 },
  { id: uuidv4(), item_id: 48, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.004400 },
  { id: uuidv4(), item_id: 49, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.004290 },
  { id: uuidv4(), item_id: 50, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.004510 },
  { id: uuidv4(), item_id: 51, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.004400 },
  { id: uuidv4(), item_id: 52, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.004400 },
  { id: uuidv4(), item_id: 53, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.005720 },
  { id: uuidv4(), item_id: 54, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.005830 },
  { id: uuidv4(), item_id: 55, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.007100 },
  { id: uuidv4(), item_id: 56, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000410 },
  { id: uuidv4(), item_id: 57, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000880 },
  { id: uuidv4(), item_id: 58, name: 'martia', token_name: 'MARTIA', amount_per_ep: 0.000220 },


  { id: uuidv4(), item_id: 4, name: 'power', token_name: 'POWER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 5, name: 'power', token_name: 'POWER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 6, name: 'power', token_name: 'POWER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 7, name: 'power', token_name: 'POWER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 8, name: 'power', token_name: 'POWER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 9, name: 'power', token_name: 'POWER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 10, name: 'power', token_name: 'POWER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 11, name: 'power', token_name: 'POWER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 12, name: 'power', token_name: 'POWER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 13, name: 'power', token_name: 'POWER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 14, name: 'power', token_name: 'POWER', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 18, name: 'power', token_name: 'POWER', amount_per_ep: 0.0007 },
  { id: uuidv4(), item_id: 19, name: 'power', token_name: 'POWER', amount_per_ep: 0.0002 },
  { id: uuidv4(), item_id: 20, name: 'power', token_name: 'POWER', amount_per_ep: 0.0006 },
  { id: uuidv4(), item_id: 37, name: 'power', token_name: 'POWER', amount_per_ep: 0.0015 },
  { id: uuidv4(), item_id: 38, name: 'power', token_name: 'POWER', amount_per_ep: 0.0004 },
  { id: uuidv4(), item_id: 39, name: 'power', token_name: 'POWER', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 40, name: 'power', token_name: 'POWER', amount_per_ep: 0.0004 },
  { id: uuidv4(), item_id: 41, name: 'power', token_name: 'POWER', amount_per_ep: 0.0005 },
  { id: uuidv4(), item_id: 42, name: 'power', token_name: 'POWER', amount_per_ep: 0.0005 },
  { id: uuidv4(), item_id: 43, name: 'power', token_name: 'POWER', amount_per_ep: 0.0005 },
  { id: uuidv4(), item_id: 44, name: 'power', token_name: 'POWER', amount_per_ep: 0.0009 },
  { id: uuidv4(), item_id: 45, name: 'power', token_name: 'POWER', amount_per_ep: 0.0006 },
  { id: uuidv4(), item_id: 46, name: 'power', token_name: 'POWER', amount_per_ep: 0.0008 },
  { id: uuidv4(), item_id: 47, name: 'power', token_name: 'POWER', amount_per_ep: 0.0004 },
  { id: uuidv4(), item_id: 48, name: 'power', token_name: 'POWER', amount_per_ep: 0.0005 },
  { id: uuidv4(), item_id: 49, name: 'power', token_name: 'POWER', amount_per_ep: 0.0004 },
  { id: uuidv4(), item_id: 50, name: 'power', token_name: 'POWER', amount_per_ep: 0.0011 },
  { id: uuidv4(), item_id: 53, name: 'power', token_name: 'POWER', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 54, name: 'power', token_name: 'POWER', amount_per_ep: 0.0008 },
  { id: uuidv4(), item_id: 55, name: 'power', token_name: 'POWER', amount_per_ep: 0.0010 },
  { id: uuidv4(), item_id: 56, name: 'power', token_name: 'POWER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 57, name: 'power', token_name: 'POWER', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 58, name: 'power', token_name: 'POWER', amount_per_ep: 0.0002 },


  { id: uuidv4(), item_id: 18, name: 'water', token_name: 'WATER', amount_per_ep: 0.0005 },
  { id: uuidv4(), item_id: 20, name: 'water', token_name: 'WATER', amount_per_ep: 0.0006 },
  { id: uuidv4(), item_id: 21, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 22, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 23, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 24, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 25, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 26, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 27, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 28, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 29, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 30, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 31, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 32, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 33, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 34, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 35, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 36, name: 'water', token_name: 'WATER', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 39, name: 'water', token_name: 'WATER', amount_per_ep: 0.0010 },
  { id: uuidv4(), item_id: 41, name: 'water', token_name: 'WATER', amount_per_ep: 0.0011 },
  { id: uuidv4(), item_id: 44, name: 'water', token_name: 'WATER', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 55, name: 'water', token_name: 'WATER', amount_per_ep: 0.0018 },
  { id: uuidv4(), item_id: 56, name: 'water', token_name: 'WATER', amount_per_ep: 0.0002 },

  { id: uuidv4(), item_id: 21, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 22, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 23, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 24, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 25, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 26, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 27, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 28, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 29, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 30, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 31, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 32, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 33, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 34, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 35, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },
  { id: uuidv4(), item_id: 36, name: 'wellbeing', token_name: 'WELLBNG', amount_per_ep: 0.0012 },

  { id: uuidv4(), item_id: 19, name: 'regolith', token_name: 'REGOLTH', amount_per_ep: 0.0008 },
  { id: uuidv4(), item_id: 45, name: 'regolith', token_name: 'REGOLTH', amount_per_ep: 0.0014 },

  { id: uuidv4(), item_id: 21, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 22, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 23, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 24, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 25, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 26, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 27, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 28, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 29, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 30, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 31, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 32, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 33, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 34, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 35, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 36, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 40, name: 'food', token_name: 'FOOD', amount_per_ep: 0.0007 },

  { id: uuidv4(), item_id: 21, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 22, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 23, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 24, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 25, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 26, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 27, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 28, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 29, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 30, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 31, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 32, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 33, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 34, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 35, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 36, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },
  { id: uuidv4(), item_id: 58, name: 'oxygen', token_name: 'OXYGEN', amount_per_ep: 0.0001 },


  { id: uuidv4(), item_id: 37, name: 'engineer labor', token_name: 'ENGLAB', amount_per_ep: 0.0002 },
  { id: uuidv4(), item_id: 39, name: 'engineer labor', token_name: 'ENGLAB', amount_per_ep: 0.0004 },
  { id: uuidv4(), item_id: 45, name: 'engineer labor', token_name: 'ENGLAB', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 47, name: 'engineer labor', token_name: 'ENGLAB', amount_per_ep: 0.0007 },
  { id: uuidv4(), item_id: 48, name: 'engineer labor', token_name: 'ENGLAB', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 51, name: 'engineer labor', token_name: 'ENGLAB', amount_per_ep: 0.0004 },
  { id: uuidv4(), item_id: 52, name: 'engineer labor', token_name: 'ENGLAB', amount_per_ep: 0.0004 },
  { id: uuidv4(), item_id: 53, name: 'engineer labor', token_name: 'ENGLAB', amount_per_ep: 0.0002 },

  { id: uuidv4(), item_id: 38, name: 'science labor', token_name: 'SCILAB', amount_per_ep: 0.0008 },
  { id: uuidv4(), item_id: 44, name: 'science labor', token_name: 'SCILAB', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 48, name: 'science labor', token_name: 'SCILAB', amount_per_ep: 0.0004 },
  { id: uuidv4(), item_id: 50, name: 'science labor', token_name: 'SCILAB', amount_per_ep: 0.0006 },
  { id: uuidv4(), item_id: 55, name: 'science labor', token_name: 'SCILAB', amount_per_ep: 0.0006 },

  { id: uuidv4(), item_id: 40, name: 'social labor', token_name: 'SOCLAB', amount_per_ep: 0.0004 },
  { id: uuidv4(), item_id: 41, name: 'social labor', token_name: 'SOCLAB', amount_per_ep: 0.0004 },
  { id: uuidv4(), item_id: 42, name: 'social labor', token_name: 'SOCLAB', amount_per_ep: 0.0007 },
  { id: uuidv4(), item_id: 43, name: 'social labor', token_name: 'SOCLAB', amount_per_ep: 0.0007 },
  { id: uuidv4(), item_id: 54, name: 'social labor', token_name: 'SOCLAB', amount_per_ep: 0.0009 },

  { id: uuidv4(), item_id: 37, name: 'logistic labor', token_name: 'LOGLAB', amount_per_ep: 0.0003 },
  { id: uuidv4(), item_id: 46, name: 'logistic labor', token_name: 'LOGLAB', amount_per_ep: 0.0006 },
  { id: uuidv4(), item_id: 49, name: 'logistic labor', token_name: 'LOGLAB', amount_per_ep: 0.0007 },
  { id: uuidv4(), item_id: 51, name: 'logistic labor', token_name: 'LOGLAB', amount_per_ep: 0.0004 },
  { id: uuidv4(), item_id: 52, name: 'logistic labor', token_name: 'LOGLAB', amount_per_ep: 0.0004 },
  { id: uuidv4(), item_id: 57, name: 'logistic labor', token_name: 'LOGLAB', amount_per_ep: 0.0001 },

  { id: uuidv4(), item_id: 53, name: 'ore', token_name: 'ORE', amount_per_ep: 0.0006 },

];
